package com.toker.sys.view.home.activity.custom.fcustomdetail

data class FCustomDBean(
    val `data`: Data,
    val code: String,
    val desc: String
){
    /**
     * 请求是否成功
     */
    fun isSuccess(): Boolean {
        return code == "1" && data != null
    }
}

data class Data(
    val customer: Customer,
    val customerRecommend: CustomerRecommend,
    val customerStateChanges: List<CustomerStateChange>
)

data class CustomerRecommend(
    val arriveAddr: Any,
    val arriveArea: Any,
    val beeFlag: Any,
    val bindingResult: Any,
    val condition: Any,
    val createTime: Long,
    val creator: String,
    val creatorId: Any,
    val customerAddress: String,
    val customerArea: String,
    val customerCity: String,
    val customerLatitude: String,
    val customerLongitude: String,
    val customerProvince: String,
    val customerStreet: String,
    val delFlag: String,
    val endTime: Any,
    val followUser: Any,
    val followUserId: Any,
    val houseType: String,
    val id: String,
    val intentionLevel: String,
    val invalidDateFlag: Long,
    val invalidReason: Any,
    val name: String,
    val page: Any,
    val pageSize: Any,
    val phone: String,
    val productAcreage: String,
    val productType: String,
    val projectId: Any,
    val projectName: Any,
    val publicTime: Long,
    val purchaseFocus: String,
    val recommendProject: String,
    val recommendTime: Any,
    val registerAddress: String,
    val registerArea: String,
    val registerCity: String,
    val registerLatitude: Any,
    val registerLongitude: Any,
    val registerProvince: String,
    val registerStreet: String,
    val remark: String,
    val sixNumbers: String,
    val startTime: Any,
    val status: String,
    val statusVal: String,
    val tableTag: String,
    val unfollowedTime: Any,
    val updateTime: Long,
    val updator: Any,
    val updatorId: Any,
    val userId: String,
    val userName: String,
    val validFlag: String,
    val visitTime: Long
)

data class Customer(
    val arriveAddr: Any,
    val arriveArea: Any,
    val beeFlag: Any,
    val bindingResult: Any,
    val condition: Any,
    val createTime: Long,
    val creator: String,
    val creatorId: Any,
    val customerAddress: String,
    val customerArea: String,
    val customerCity: String,
    val customerLatitude: String,
    val customerLongitude: String,
    val customerProvince: String,
    val customerStreet: String,
    val delFlag: String,
    val endTime: Any,
    val followUser: Any,
    val followUserId: Any,
    val houseType: String,
    val id: String,
    val intentionLevel: String,
    val invalidDateFlag: Long,
    val invalidReason: Any,
    val name: String,
    val page: Any,
    val pageSize: Any,
    val phone: String,
    val productAcreage: String,
    val productType: String,
    val projectId: Any,
    val projectName: Any,
    val publicTime: Long,
    val purchaseFocus: String,
    val recommendProject: String,
    val recommendTime: Any,
    val registerAddress: String,
    val registerArea: String,
    val registerCity: String,
    val registerLatitude: Any,
    val registerLongitude: Any,
    val registerProvince: String,
    val registerStreet: String,
    val remark: String,
    val sixNumbers: String,
    val startTime: Any,
    val status: String,
    val statusVal: String,
    val tableTag: String,
    val unfollowedTime: Any,
    val updateTime: Long,
    val updator: Any,
    val updatorId: Any,
    val userId: String,
    val userName: String,
    val validFlag: String,
    val visitTime: Long
)

data class CustomerStateChange(
    val changeTime: Long,
    val content: String,
    val id: String,
    val recommendId: String,
    val status: String,
    val tableTag: String,
    val userName: String
)